<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_base57424b87a09fe',
	'title' => 'Code Injection',
	'fields' => array (
		array (
			'key' => 'field_base57424b9d724c0',
			'label' => 'Head Code',
			'name' => 'code_inject_head',
			'type' => 'textarea',
			'instructions' => 'Enter code that will be injected into the `head` tag on every page of your site.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_base57424bf1724c1',
			'label' => 'Footer Code',
			'name' => 'footer_code',
			'type' => 'textarea',
			'instructions' => 'Enter code that will be injected before the closing `body` tag on every page of your site.
',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-code-injection',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_base5742458f85965',
	'title' => 'Contact Info',
	'fields' => array (
		array (
			'key' => 'field_base5742459874094',
			'label' => 'Physical Address',
			'name' => 'contact_address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'wpautop',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_base574245ef55155',
			'label' => 'Phone Number',
			'name' => 'contact_phone',
			'type' => 'text',
			'instructions' => 'This number will be made public on your website.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '(xxx) xxx-xxxx',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_base5742463755156',
			'label' => 'Email',
			'name' => 'contact_email',
			'type' => 'email',
			'instructions' => 'This email address will be public on your website.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'xx@xxxxxx.com',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_base5742493e20b17',
			'label' => 'Facebook URL',
			'name' => 'contact_facebook_url',
			'type' => 'url',
			'instructions' => 'Example: https://facebook.com/yourfacebook',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_base5742497c20b18',
			'label' => 'Twitter URL',
			'name' => 'contact_twitter_url',
			'type' => 'url',
			'instructions' => 'Example: https://twitter.com/yourtwitter',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_base5742499920b19',
			'label' => 'LinkedIn URL',
			'name' => 'contact_linkedin_url',
			'type' => 'url',
			'instructions' => 'Example: https://linkedin.com/in/yourlinkedin',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_base574249ca20b1a',
			'label' => 'Instagram URL',
			'name' => 'contact_instagram_url',
			'type' => 'url',
			'instructions' => 'Example: https://www.instagram.com/yourinstagram',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array (
			'key' => 'field_base574249e420b1b',
			'label' => 'Google Plus URL',
			'name' => 'contact_google_plus_url',
			'type' => 'url',
			'instructions' => 'Example: https://plus.google.com/+yourgoogleplus',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-contact-info',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_base57424b1ddfe44',
	'title' => 'External Services',
	'fields' => array (
		array (
			'key' => 'field_base57424b2f4f19f',
			'label' => 'Google Analytics ID',
			'name' => 'google_analytics_id',
			'type' => 'text',
			'instructions' => 'Note: Universal Analytics only, not Classic Analytics',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'UA-XXXXX-YY',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-external-services',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_base574250c089114',
	'title' => 'Google Maps Api Key',
	'fields' => array (
		array (
			'key' => 'field_base574250dc5c5da',
			'label' => 'Google Maps API key',
			'name' => 'google_maps_api_key',
			'type' => 'text',
			'instructions' => 'https://developers.google.com/maps/documentation/javascript/tutorial?authuser=1#Loading_the_Maps_API',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-external-services',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_base57424c1266229',
	'title' => 'Site Alert',
	'fields' => array (
		array (
			'key' => 'field_base57424c633300e',
			'label' => 'Alert Status',
			'name' => 'alert_status',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'off' => 'Off',
				'on' => 'On',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'off',
			'layout' => 'horizontal',
		),
		array (
			'key' => 'field_base57424c9d3300f',
			'label' => 'Alert Text',
			'name' => 'alert_text',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-site-alerts',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
